<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <TargetPlatformVersion>10.0.26100.0</TargetPlatformVersion>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>DS Battery OSD</AssemblyName>
    <RootNamespace>DsBatteryOsd</RootNamespace>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
    <SatelliteResourceLanguages>ja</SatelliteResourceLanguages>

  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\Nunito.ttf" />
    <None Update="Assets\OFL-Nunito.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2705" PrivateAssets="all" />
  </ItemGroup>
</Project>
