<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>DS Battery OSD</AssemblyName>
    <RootNamespace>DsBatteryOsd</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\Nunito.ttf" />
    <None Update="Assets\OFL-Nunito.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
